# Array:
 - Array is similar to list
 
 int array - All the Value should be in integer
 float array - All the Value should be in float

In [2]:
from array import *
vals = array('i',[5,8,4,3,2,8])
vals

array('i', [5, 8, 4, 3, 2, 8])

In [3]:
vals = array('i',[5,3.4,6,7.2])
vals

TypeError: integer argument expected, got float

In [15]:
vals = array('f',[2,3.4,5.6,7])
vals

array('f', [2.0, 3.4000000953674316, 5.599999904632568, 7.0])

In [16]:
vals = array('f',[2.2,3.4,5.6,7.8])
vals

array('f', [2.200000047683716, 3.4000000953674316, 5.599999904632568, 7.800000190734863])

In [6]:
vals.buffer_info()

(381250580176, 6)

In [9]:
for i in range(5):
    print(vals[i])

5
8
4
3
2


In [12]:
for i in range(len(vals)):
    print(vals[i])

5
8
4
3
2
8


In [14]:
val = array('u',['a','e','i','o','u'])
val

array('u', 'aeiou')

In [18]:
from array import *
arr = array('i',[])
n = int(input("Enter Total Value"))
for i in range(n):
    x=int(input("Enter Next Value"))
    arr.append(x)
print(arr)

Enter Total Value3
Enter Next Value1
Enter Next Value2
Enter Next Value3
array('i', [1, 2, 3])


Numpy in array:
Array - Only Support single dimensional
Numpy - Support Multidimensional Array
- Easy to do scientific calculations
- Before  using numpy install 
 e.g.   PIP3 install numpy
- If you are working with anaconda distribution numpy will be installed by default

# 6 Ways to create array in Numpy 

1) array()
2) linspace()
3) logspace()
4) arange()
5) zeros()
6) ones()

In [20]:
import numpy as np
ar = np.array([2,5,6,3,2,1])
ar

array([2, 5, 6, 3, 2, 1])

In [21]:
ar[0]

2

In [22]:
ar[-1]

1

In [24]:
ar[2:]

array([6, 3, 2, 1])

In [25]:
ar.dtype

dtype('int32')

In [26]:
ar1 = np.array([2,5,6,2,5.4,7.4])
ar1

array([2. , 5. , 6. , 2. , 5.4, 7.4])

In [28]:
ar1.dtype

dtype('float64')

# linspace  - linspace(first,last,divide into part)

In [34]:
arr2 = np.linspace(1,20,5)
arr2

array([ 1.  ,  5.75, 10.5 , 15.25, 20.  ])

# logspace - diff with log value

In [39]:
arr3 = np.logspace(1,20,5)
arr3
print('%2f' %arr3[4])

100000000000000000000.000000


# arange 

In [41]:
from numpy import *
arr4 = arange(1,20,5)
arr4

array([ 1,  6, 11, 16])

# Zeros

In [42]:
arr5 = zeros(5)
arr5

array([0., 0., 0., 0., 0.])

# Ones

In [43]:
arr6 = ones(5)
arr6

array([1., 1., 1., 1., 1.])

# ************************ Operations in array************************

In [44]:
arr = array([1,2,3,4,5,6])
arr = arr + 5
arr

array([ 6,  7,  8,  9, 10, 11])

In [46]:
arr1 =  array([1,2,3,4,5,6])
arr2 =  array([2,2,2,2,2,2])
arr = arr1 + arr2
arr

array([3, 4, 5, 6, 7, 8])

In [47]:
sin(arr)

array([ 0.14112001, -0.7568025 , -0.95892427, -0.2794155 ,  0.6569866 ,
        0.98935825])

In [48]:
cos(arr)

array([-0.9899925 , -0.65364362,  0.28366219,  0.96017029,  0.75390225,
       -0.14550003])

In [49]:
log(arr)

array([1.09861229, 1.38629436, 1.60943791, 1.79175947, 1.94591015,
       2.07944154])

In [50]:
sqrt(arr)

array([1.73205081, 2.        , 2.23606798, 2.44948974, 2.64575131,
       2.82842712])

In [52]:
sum(arr)

33

In [53]:
min(arr)

3

In [54]:
max(arr)

8

In [55]:
sort(arr)

array([3, 4, 5, 6, 7, 8])

In [57]:
ar1 = array([2,4,2,5,3])
ar2 = ar1
arr1

array([1, 2, 3, 4, 5, 6])

In [58]:
arr2

array([2, 2, 2, 2, 2, 2])

In [59]:
id(arr1)

381281978688

In [60]:
id(arr2)

381281978128