# Matrix in python:
- 1D
- 2D

In [5]:
from numpy import *
arr1 = array([[1,2,3],[2,3,4]])
arr1

array([[1, 2, 3],
       [2, 3, 4]])

In [6]:
arr1.dtype

dtype('int32')

In [7]:
arr1.ndim

2

In [8]:
arr1.shape

(2, 3)

In [9]:
arr1.size

6

In [12]:
arr2 = arr1.flatten()
arr2

array([1, 2, 3, 2, 3, 4])

# Converting 1D to 2D

In [13]:
arr1 = array([[1,2,3,4,5,6],[7,8,9,2,3,3]])
arr1

array([[1, 2, 3, 4, 5, 6],
       [7, 8, 9, 2, 3, 3]])

In [15]:
arr1.reshape(3,4)

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 2, 3, 3]])

In [16]:
arr1.reshape(4,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [2, 3, 3]])

In [17]:
arr1.reshape(2,2,3)

array([[[1, 2, 3],
        [4, 5, 6]],

       [[7, 8, 9],
        [2, 3, 3]]])

In [20]:
m  = matrix['1 2 3 : 4 3 4']
m

TypeError: 'type' object is not subscriptable